"""Symbolic quantum circuit module"""

from qiskit.circuit.controlledgate import ControlledGate
from .library import (
    CPhaseGate,
    CRGate,
    CRXGate,
    CRYGate,
    CRZGate,
    CHGate,
    CSGate,
    CSXGate,
    CSXdgGate,
    CSdgGate,
    CTGate,
    CTdgGate,
    CU1Gate,
    CU2Gate,
    CU3Gate,
    CUGate,
    CXGate,
    CYGate,
    CZGate,
    DCXGate,
    ECRGate,
    HGate,
    IGate,
    PhaseGate,
    RGate,
    RXGate,
    RXXGate,
    RYGate,
    RYYGate,
    RZGate,
    RZZGate,
    SGate,
    SXGate,
    SXdgGate,
    SdgGate,
    SwapGate,
    TGate,
    TdgGate,
    U1Gate,
    U2Gate,
    U3Gate,
    UGate,
    XGate,
    YGate,
    ZGate,
    iSwapGate,
)


name2class = {
    "id": IGate,
    "x": XGate,
    "cx": CXGate,
    "y": YGate,
    "cy": CYGate,
    "z": ZGate,
    "cz": CZGate,
    "h": HGate,
    "ch": CHGate,
    "sx": SXGate,
    "sxdg": SXdgGate,
    "csx": CSXGate,
    "csxdg": CSXdgGate,
    "s": SGate,
    "sdg": SdgGate,
    "cs": CSGate,
    "csdg": CSdgGate,
    "t": TGate,
    "tdg": TdgGate,
    "ct": CTGate,
    "ctdg": CTdgGate,
    "swap": SwapGate,
    "iswap": iSwapGate,
    "dcx": DCXGate,
    "ecr": ECRGate,
    "u": UGate,
    "cu": CUGate,
    "u1": U1Gate,
    "cu1": CU1Gate,
    "u2": U2Gate,
    "cu2": CU2Gate,
    "u3": U3Gate,
    "cu3": CU3Gate,
    "rx": RXGate,
    "crx": CRXGate,
    "ry": RYGate,
    "cry": CRYGate,
    "rz": RZGate,
    "crz": CRZGate,
    "p": PhaseGate,
    "cp": CPhaseGate,
    "r": RGate,
    "cr": CRGate,
    "rxx": RXXGate,
    "ryy": RYYGate,
    "rzz": RZZGate,
}


def get_gates():
    """todo"""
    return set(name2class.keys())


def get_class(op):
    """todo"""
    is_controlled = isinstance(op, ControlledGate)
    name = "c" + op.base_gate.name if is_controlled else op.name
    return name2class[name]


__all__ = [
    "name2class",
    "get_gates",
    "get_class",
    "IGate",
    "XGate",
    "CXGate",
    "YGate",
    "CYGate",
    "ZGate",
    "CZGate",
    "HGate",
    "CHGate",
    "CHGate",
    "SXGate",
    "SXdgGate",
    "CSXGate",
    "CSXdgGate",
    "SGate",
    "SdgGate",
    "CSGate",
    "CSdgGate",
    "TGate",
    "TdgGate",
    "CTGate",
    "CTdgGate",
    "SwapGate",
    "iSwapGate",
    "DCXGate",
    "ECRGate",
    "UGate",
    "CUGate",
    "U1Gate",
    "CU1Gate",
    "U2Gate",
    "CU2Gate",
    "U3Gate",
    "CU3Gate",
    "RXGate",
    "CRXGate",
    "RYGate",
    "CRYGate",
    "RZGate",
    "CRZGate",
    "PhaseGate",
    "CPhaseGate",
    "RGate",
    "CRGate",
    "RXXGate",
    "RYYGate",
    "RZZGate",
]
